const mongoose = require('mongoose');
const HomePageSchema = new mongoose.Schema({
    slider1:{
        image:{
            type:String,
        },
        title:{
            type:String,
        },
        paragraph:{
            type:String,
        },
        description:{
            type:String,
        },
        link:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Products'
        }
    },
    slider2:{
        image:{
            type:String,
        },
        title:{
            type:String,
        },
        paragraph:{
            type:String,
        },
        description:{
            type:String,
        },
        link:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Products'
        }
    },
    slider3:{
        image:{
            type:String,
        },
        title:{
            type:String,
        },
        paragraph:{
            type:String,
        },
        description:{
            type:String,
        },
        link:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Products'
        }
    },
    slider4:{
        image:{
            type:String,
        },
        title:{
            type:String,
        },
        paragraph:{
            type:String,
        },
        description:{
            type:String,
        },
        link:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Products'
        }
    },
    AboutSection:{
        image:{
            type:String,
        },
        title:{
            type:String,
        },
        subTitle:{
            type:String,
        },
        description1:{
            type:String,
        },
        description2:{
            type:String,
        },
    },
    HintSection:{
        title:String,
        name:String,
        image:String,
        description:String,
    }
}, { timestamps: true });
module.exports = mongoose.model('HomePage', HomePageSchema);